version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jokesdb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db/jokesdb
      API_KEY: tr6wAyc&y98e93sdnab%djasd
    depends_on:
      - db
    ports:
      - "8001:8001"
